..\..\..\Code06\build\src\autotester\Release\autotester.exe source.txt MultiClause.txt out-MultiClause.xml
..\..\..\Code06\build\src\autotester\Release\autotester.exe source.txt Calls.txt out-Calls.xml
..\..\..\Code06\build\src\autotester\Release\autotester.exe source.txt CallsT.txt out-CallsT.xml
..\..\..\Code06\build\src\autotester\Release\autotester.exe source.txt Next.txt out-Next.xml
..\..\..\Code06\build\src\autotester\Release\autotester.exe source.txt NextT.txt out-NextT.xml
..\..\..\Code06\build\src\autotester\Release\autotester.exe source.txt Modifies.txt out-Modifies.xml
..\..\..\Code06\build\src\autotester\Release\autotester.exe source.txt Uses.txt out-Uses.xml
..\..\..\Code06\build\src\autotester\Release\autotester.exe source.txt Affects.txt out-Affects.xml
..\..\..\Code06\build\src\autotester\Release\autotester.exe source.txt AffectsT.txt out-AffectsT.xml
..\..\..\Code06\build\src\autotester\Release\autotester.exe source.txt Boolean.txt out-Boolean.xml
..\..\..\Code06\build\src\autotester\Release\autotester.exe source.txt Tuple.txt out-Tuple.xml
